### ISSUE TITLE
Центрирование элементов

### ISSUE THREAD

**Issue by humakl** [Anonim-Nonameov/hasan#1]
Для img с классом .avatar, попробуй "margin: 0 auto;" - для центрирования и убери "margin-left", чтоб на экранах разных размеров все было по центру.

П.С. Чтоб проверить, как ведет себя страница на экранах разных размеров, достаточно поиграться с размером окна браузера.
![001](https://user-images.githubusercontent.com/63689727/105948863-299cf080-6085-11eb-9e7d-0293e2c31221.png)
![002](https://user-images.githubusercontent.com/63689727/105948867-2ace1d80-6085-11eb-8b24-a54a89617ef2.png)

**Comment by Anonim-Nonameov** [comment]
Сделал, в итоге аватарка сместилась на своё изначальное местоположение.

**Comment by humakl** [comment]
Не получилось, потому что <img> - строчный элемент, а центрирование с помощью "margin: 0 auto;" работает для блочных элементов. Поменяй свойство display для <img> на block и попробуй.

**Comment by Anonim-Nonameov** [comment]
Сработало! джазакаЛлаху хайран.

**Comment by humakl** [comment]
Wa iyyaka

**Comment by Anonim-Nonameov** [comment]
Ошибка исправлена.
